name: metagenomics_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - fastqc
  - fastp
  - multiqc
  - kneaddata
  - bowtie2
  - samtools
  - kraken2
  - bracken
  - krona
